#!/usr/bin/env node
// materialize-packs.mjs — write source/ + tokens.css next to each harvested shot.
//
//   node corpus/materialize-packs.mjs
//
// Shots come from harvest.mjs (network). This step is local: copy the kit voice
// sheet and the 3 must-read source files into the pack so cite/compare/doctor
// do not depend on ~/design-corpus at read time.

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";
import { collectCorpusSource, inspectPack } from "./pack-files.mjs";

const SHINE = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CORPUS = resolve(process.env.DESIGN_CORPUS || join(homedir(), "design-corpus"));
const PACKS = join(SHINE, "corpus/packs");
const EXTRACT = join(SHINE, "corpus/extracted");
const catalog = JSON.parse(readFileSync(join(SHINE, "corpus/templates.json"), "utf8"));
const byId = new Map((catalog.templates ?? []).map((t) => [t.id, t]));

const only = process.argv.slice(2).filter((a) => !a.startsWith("-"));
const dirs = readdirSync(PACKS).filter((d) => !d.startsWith(".") && (only.length ? only.includes(d) : true));

const ok = [];
const failed = [];

for (const id of dirs) {
  const row = byId.get(id);
  const dir = join(PACKS, id);
  if (!row) {
    failed.push(`${id}: pack has no catalog row`);
    continue;
  }
  const family = row.dna?.family || "shine";
  const voice = join(SHINE, "tokens/voices", `${family}.css`);
  const fallback = join(SHINE, "tokens/voices/shine.css");
  const sheet = existsSync(voice) ? voice : fallback;
  if (!existsSync(sheet)) {
    failed.push(`${id}: no voice sheet for ${family}`);
    continue;
  }
  const header =
    `/* GENERATED BY shine corpus/materialize-packs.mjs — kit paint for ${id} (${family}).\n` +
    `   Source of truth: tokens/voices/${basename(sheet)}. Do not edit. */\n`;
  const body = readFileSync(sheet, "utf8").replace(/^\/\* GENERATED BY shine corpus\/materialize-packs[\s\S]*?\*\/\n/, "");
  writeFileSync(join(dir, "tokens.css"), header + (body.startsWith("/*") ? body : `\n${body}`));

  const { show, files } = collectCorpusSource(row, { corpus: CORPUS, extractDir: EXTRACT });
  const picks = show.length ? show : files.slice(0, 3);
  if (!picks.length) {
    failed.push(`${id}: no corpus source at ${row.path || "(none)"} — run corpus/acquire.sh`);
    continue;
  }
  const srcDir = join(dir, "source");
  rmSync(srcDir, { recursive: true, force: true });
  mkdirSync(srcDir, { recursive: true });
  const used = new Set();
  for (const src of picks) {
    let name = basename(src);
    if (used.has(name)) name = relative(CORPUS, src).replace(/[\\/]/g, "__");
    used.add(name);
    writeFileSync(join(srcDir, name), readFileSync(src));
  }
  const broken = inspectPack(dir, family);
  if (broken.length) failed.push(`${id}: ${broken.join("; ")}`);
  else ok.push(`${id} (${picks.map((p) => basename(p)).join(", ")})`);
}

console.log(`materialize: ${ok.length} packs, ${failed.length} failed`);
for (const line of ok) console.log(`ok    ${line}`);
if (failed.length) {
  console.error(`failed:\n  ${failed.join("\n  ")}`);
  process.exit(1);
}
