#!/usr/bin/env node
import {readFileSync,writeFileSync,existsSync,realpathSync,readdirSync} from 'node:fs';
import {join,resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {sourceInventory,sourceGraph} from './blocks.mjs';
import {execFileSync} from 'node:child_process';
import {load} from '../verify/deps.mjs';
import {runStep} from '../verify/usability.mjs';
const hash=value=>createHash('sha256').update(value).digest('hex');
export function surfaceCensus(project){const ts=load('typescript'),files=sourceInventory(project).filter(file=>!(/fixture/i.test(file.path))),routes=files.filter(file=>/(?:^|\/)app\/(?:.*\/)?page\.[jt]sx?$/.test(file.path)&&!file.path.includes('/api/')).map(file=>({source:file.path,sha256:file.sha256})),controls=[];
 for(const file of files){const ast=ts.createSourceFile(file.path,readFileSync(join(project,file.path),'utf8'),ts.ScriptTarget.Latest,true);const kinds=[];const visit=node=>{if(ts.isJsxOpeningElement(node)||ts.isJsxSelfClosingElement(node)){const tag=node.tagName.getText(ast);if(/^(button|input|select|textarea|form|table|nav|Button|Input|Select|Textarea|DataGrid|DataTable|.*Chart|.*Dialog|.*Tabs|.*Picker|.*Upload)$/.test(tag))kinds.push(tag);}ts.forEachChild(node,visit);};visit(ast);if(kinds.length)controls.push({source:file.path,kinds:[...new Set(kinds)].sort(),count:kinds.length,sha256:file.sha256});}
 const supporting=[];const scan=dir=>{if(!existsSync(dir))return;for(const entry of readdirSync(dir,{withFileTypes:true})){if(entry.isSymbolicLink()||entry.name.startsWith('.')||['node_modules','dist','build','coverage'].includes(entry.name))continue;const path=join(dir,entry.name);if(entry.isDirectory())scan(path);else if(/\.(css|json)$/.test(entry.name))supporting.push([path.slice(resolve(project).length+1),hash(readFileSync(path))]);}};for(const dir of ['src','app','styles'])scan(join(resolve(project),dir));for(const file of ['package.json','package-lock.json','components.json','tsconfig.json','next.config.ts','next.config.mjs','tailwind.config.ts','tailwind.config.js'])if(existsSync(join(project,file)))supporting.push([file,hash(readFileSync(join(project,file)))]);return {routes,controls,fingerprint:hash(JSON.stringify([...files.map(file=>[file.path,file.sha256]),...supporting.sort((a,b)=>a[0].localeCompare(b[0]))]))};}
export function validateSurfaceContract(project,contract){const census=surfaceCensus(project),errors=[];if(contract?.version!==1||!Array.isArray(contract.routes)||!contract.routes.length)return {status:'failed',errors:['Nonempty route population required'],census};const widths=contract.widths||[390,1440];if(!widths.length||new Set(widths).size!==widths.length||widths.some(width=>!Number.isInteger(width)||width<320||width>3840))errors.push('Invalid or duplicate viewport widths');const ids=new Set(),sources=new Set();for(const route of contract.routes){if(!route.id||ids.has(route.id))errors.push('Duplicate or missing route id');ids.add(route.id);sources.add(route.source);if(!census.routes.some(row=>row.source===route.source))errors.push('Unknown route source: '+route.source);if(!route.url?.startsWith('/')||route.url.startsWith('//'))errors.push('Route must be same-origin: '+route.id);if(route.destination&&(!route.destination.startsWith('/')||route.destination.startsWith('//')))errors.push('Route destination must be same-origin');if(!Array.isArray(route.requiredStates)||!route.requiredStates.length)errors.push('Declare required states: '+route.id);const stateIds=new Set();for(const state of route.states||[]){if(!state.id||stateIds.has(state.id))errors.push('Duplicate or missing state: '+route.id);stateIds.add(state.id);if(state.destination&&(!state.destination.startsWith('/')||state.destination.startsWith('//')))errors.push('State destination must be same-origin');if(state.path&&(!state.path.startsWith('/')||state.path.startsWith('//')))errors.push('State path must be same-origin');if(!state.steps?.length||!state.steps.some(step=>['visible','text','value','checked','count','enabled','disabled'].includes(step.action)))errors.push('State needs observable assertions: '+route.id+'/'+state.id);if(state.id!=='ready'&&!state.steps.some(step=>['click','fill','press','select'].includes(step.action)))errors.push('Non-ready state needs a real workflow action: '+route.id+'/'+state.id);}for(const state of route.requiredStates||[])if(!stateIds.has(state))errors.push('Missing state '+route.id+'/'+state);}
 for(const route of census.routes)if(!sources.has(route.source))errors.push('Unclassified route: '+route.source);
 const graph=sourceGraph(project),graphs=new Map();
 for(const route of contract.routes){if(!census.routes.some(row=>row.source===route.source))continue;const reachable=graph(route.source);let dir=dirname(resolve(project,route.source));while(dir.startsWith(resolve(project))){for(const name of ['layout.tsx','layout.jsx','layout.ts','layout.js'])if(existsSync(join(dir,name)))for(const file of graph(join(dir,name)))reachable.add(file);if(dir===resolve(project))break;dir=dirname(dir);}graphs.set(route.id,reachable);}
 const owners=contract.controlOwners||[];if(new Set(owners.map(row=>row.source)).size!==owners.length)errors.push('Duplicate control owners');for(const file of census.controls){const owner=owners.find(row=>row.source===file.source);if(!owner||owner.reason?.trim().length<20||!owner.proofs?.length)errors.push('Unclassified controls: '+file.source);else for(const proof of owner.proofs){const route=contract.routes.find(row=>row.id===proof.route);if(!route?.states?.some(state=>state.id===proof.state))errors.push('Missing control proof '+file.source+': '+proof.route+'/'+proof.state);else if(!graphs.get(proof.route)?.has(realpathSync(join(project,file.source))))errors.push('Control proof route does not import '+file.source);}}
 for(const owner of owners)if(!census.controls.some(file=>file.source===owner.source))errors.push('Stale control owner: '+owner.source);
 return {status:errors.length?'failed':'passed',errors,census,routeCases:contract.routes.reduce((n,route)=>n+(route.states?.length||0),0)};}
export function verifySurfaceReceipt(project,contract,receipt,{maxAgeHours=24}={}){const validation=validateSurfaceContract(project,contract),errors=[...validation.errors];if(receipt?.kind!=='shine-surface-audit'||receipt.version!==1)errors.push('Missing generated route/state audit receipt');if(receipt?.sourceFingerprint!==validation.census.fingerprint)errors.push('Source changed since workflow proof');if(receipt?.contractSha256!==hash(JSON.stringify(contract)))errors.push('Contract changed since workflow proof');try{if(receipt?.sourceCommit!==execFileSync('git',['-C',project,'rev-parse','HEAD'],{encoding:'utf8'}).trim())errors.push('Missing or mismatched source commit');}catch{errors.push('Source commit is unavailable');}const expectedCount=(contract.routes||[]).reduce((n,route)=>n+(route.states?.length||0),0)*(contract.widths||[390,1440]).length;if(receipt?.results?.length!==expectedCount||new Set((receipt?.results||[]).map(row=>[row.route,row.state,row.width].join('/'))).size!==expectedCount)errors.push('Duplicate or unexpected workflow results');const age=Date.now()-Date.parse(receipt?.createdAt);if(!Number.isFinite(age)||age< -60000||age>maxAgeHours*3600000)errors.push('Workflow proof is stale');for(const route of contract.routes||[])for(const state of route.states||[]){for(const width of contract.widths||[390,1440])if(!receipt?.results?.some(row=>row.route===route.id&&row.state===state.id&&row.width===width&&row.status==='passed'))errors.push('Missing passed workflow '+route.id+'/'+state.id+'/'+width);}return {status:errors.length?'failed':'passed',errors,routes:contract.routes?.length||0,states:validation.routeCases};}
export async function runSurfaceAudit(project,contract,{base,storageState,output}){const validation=validateSurfaceContract(project,contract);if(validation.status!=='passed')throw Error(validation.errors.join('\n'));const commit=execFileSync('git',['-C',project,'rev-parse','HEAD'],{encoding:'utf8'}).trim();if((contract.sourceCommit&&commit!==contract.sourceCommit)||execFileSync('git',['-C',project,'status','--porcelain'],{encoding:'utf8'}).trim())throw Error('Clean source commit matching contract is required');const {chromium}=load('playwright'),browser=await chromium.launch(),results=[];try{const context=await browser.newContext({storageState});for(const route of contract.routes)for(const state of route.states)for(const width of contract.widths||[390,1440]){const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));try{await page.setViewportSize({width,height:1000});const response=await page.goto(new URL(state.path||route.url,base).href,{waitUntil:'networkidle',timeout:90000});if(response.status()!==200)throw Error('HTTP '+response.status());const expected=new URL(state.destination||route.destination||state.path||route.url,base);if(new URL(page.url()).origin!==expected.origin||new URL(page.url()).pathname.replace(/\/$/,'')!==expected.pathname.replace(/\/$/,''))throw Error('Unexpected navigation or authentication redirect');if(!contract.buildHeader||response.headers()[contract.buildHeader.toLowerCase()]!==commit)throw Error('Rendered build does not match the contract source commit');for(const step of state.steps)await runStep(page,step);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('Page overflow');if(errors.length)throw Error(errors.join('; '));results.push({route:route.id,state:state.id,width,status:'passed',assertions:state.steps.length,url:page.url()});}catch(error){results.push({route:route.id,state:state.id,width,status:'failed',error:error.message});}finally{await page.close();}}await context.close();}finally{await browser.close();}if(surfaceCensus(project).fingerprint!==validation.census.fingerprint)throw Error('Source changed while browser proof ran');const receipt={sourceCommit:commit,version:1,kind:'shine-surface-audit',createdAt:new Date().toISOString(),sourceFingerprint:validation.census.fingerprint,contractSha256:hash(JSON.stringify(contract)),results};const verdict=verifySurfaceReceipt(project,contract,receipt);receipt.status=verdict.status;writeFileSync(output,JSON.stringify(receipt,null,2)+'\n');return {...verdict,output};}
if(process.argv[1]&&existsSync(process.argv[1])&&realpathSync(process.argv[1])===fileURLToPath(import.meta.url)){const a=process.argv.slice(2),opt=n=>a.includes(n)?a[a.indexOf(n)+1]:undefined,p=resolve(opt('--project')||'.'),path=opt('--contract');let result=surfaceCensus(p);if(path){const c=JSON.parse(readFileSync(path,'utf8'));result=opt('--run')?await runSurfaceAudit(p,c,{base:opt('--run'),storageState:opt('--storage-state'),output:opt('--out')||'shine-surface-receipt.json'}):opt('--receipt')?verifySurfaceReceipt(p,c,JSON.parse(readFileSync(opt('--receipt'),'utf8'))):validateSurfaceContract(p,c);}console.log(JSON.stringify(result,null,2));if(result.status==='failed')process.exitCode=1;}
