#!/usr/bin/env node
import {readFileSync,writeFileSync,existsSync,mkdirSync,mkdtempSync,rmSync,realpathSync} from 'node:fs';
import {join,resolve,dirname,relative} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {checkCompatibility} from './compatibility.mjs';
const root=fileURLToPath(new URL('..',import.meta.url));
export const digest=text=>createHash('sha256').update(text).digest('hex');
export function adaptSource(source,prefix=''){if(!prefix)return source;return source.replace(/className="([^"]*)"/g,(_,value)=>'className="'+value.split(/\s+/).map(token=>token?prefix+':'+token:token).join(' ')+'"');}
function safe(project,path){const root=realpathSync(project),file=resolve(root,path);let ancestor=file;while(!existsSync(ancestor))ancestor=dirname(ancestor);if(relative(root,file).startsWith('..')||relative(root,realpathSync(ancestor)).startsWith('..'))throw Error('Managed source must stay inside the project');return file;}
export function trackBlock(project,id,path){const catalog=JSON.parse(readFileSync(join(root,'blocks/catalog.json'),'utf8')).blocks;if(!catalog.some(row=>row.id===id))throw Error('Unknown block '+id);const config=JSON.parse(readFileSync(join(project,'components.json'),'utf8'));const prefix=config.tailwind?.prefix||'',upstream=readFileSync(join(root,'blocks',id+'.tsx'),'utf8'),base=adaptSource(upstream,prefix),local=readFileSync(safe(project,path),'utf8');const manifestPath=join(project,'shine-installation.json'),manifest=existsSync(manifestPath)?JSON.parse(readFileSync(manifestPath,'utf8')):{version:1,blocks:[]};if(manifest.version!==1||!Array.isArray(manifest.blocks))throw Error('Invalid installation manifest');if(manifest.blocks.some(row=>row.id===id||row.path===path))throw Error('Already tracked; use upgrade');const baseline='.shine/baselines/'+id+'.tsx';mkdirSync(dirname(safe(project,baseline)),{recursive:true});writeFileSync(safe(project,baseline),base);manifest.blocks.push({id,path,prefix,baseline,upstreamSha256:digest(upstream),baselineSha256:digest(base),initialLocalSha256:digest(local)});writeFileSync(manifestPath,JSON.stringify(manifest,null,2)+'\n');return {id,modified:local!==base};}
export function planUpgrade(project,{apply=false}={}){const path=join(project,'shine-installation.json'),manifest=JSON.parse(readFileSync(path,'utf8'));if(manifest.version!==1||!manifest.blocks.length)throw Error('Nonempty version 1 installation manifest required');const catalog=JSON.parse(readFileSync(join(root,'blocks/catalog.json'),'utf8')).blocks;if(new Set(manifest.blocks.map(row=>row.id)).size!==manifest.blocks.length||new Set(manifest.blocks.map(row=>row.path)).size!==manifest.blocks.length)throw Error('Duplicate managed blocks or paths');for(const item of manifest.blocks)if(!catalog.some(row=>row.id===item.id))throw Error('Unknown managed block '+item.id);const results=[],writes=[];for(const item of manifest.blocks){const file=safe(project,item.path),baseline=safe(project,item.baseline),base=readFileSync(baseline,'utf8'),local=readFileSync(file,'utf8'),source=readFileSync(join(root,'blocks',item.id+'.tsx'),'utf8'),next=adaptSource(source,item.prefix);if(digest(base)!==item.baselineSha256)throw Error('Baseline changed: '+item.id);let merged=local,status=next===base?(local===base?'current':'locally-modified'):'update';if(next!==base){if(local===base)merged=next;else{const temp=mkdtempSync(join(tmpdir(),'shine-merge-'));try{for(const [name,value]of Object.entries({local,base,next}))writeFileSync(join(temp,name),value);const run=spawnSync('git',['merge-file','-p',join(temp,'local'),join(temp,'base'),join(temp,'next')],{encoding:'utf8'});if(run.status!==0){status='conflict';merged=null;}else{status='merged';merged=run.stdout;}}finally{rmSync(temp,{recursive:true,force:true});}}}results.push({id:item.id,path:item.path,status,localSha256:digest(local),upstreamSha256:digest(source)});if(merged!==null&&next!==base)writes.push({item,file,baseline,merged,next,source});}
 const conflicts=results.filter(row=>row.status==='conflict');if(apply&&conflicts.length)throw Error('No files changed. Resolve conflicts: '+conflicts.map(row=>row.id).join(', '));if(apply&&writes.length){const compatibility=checkCompatibility(project,writes.map(write=>write.item.path),{sources:Object.fromEntries(writes.map(write=>[write.item.path,write.merged]))});if(compatibility.status!=='passed')throw Error('No files changed. Incompatible upgrade: '+compatibility.errors.join('; '));}if(apply){const backups=new Map([path,...writes.flatMap(write=>[write.file,write.baseline])].map(file=>[file,readFileSync(file)]));try{for(const write of writes){writeFileSync(write.file,write.merged);writeFileSync(write.baseline,write.next);write.item.upstreamSha256=digest(write.source);write.item.baselineSha256=digest(write.next);}writeFileSync(path,JSON.stringify(manifest,null,2)+'\n');}catch(error){const failures=[];for(const [file,content] of backups)try{writeFileSync(file,content);}catch(cause){failures.push(file+': '+cause.message);}throw Error('Upgrade failed; rollback '+(failures.length?'needs recovery: '+failures.join('; '):'restored original files')+'. '+error.message);}}return {status:conflicts.length?'conflict':'passed',applied:apply,blocks:results};}
if(process.argv[1]&&existsSync(process.argv[1])&&realpathSync(process.argv[1])===fileURLToPath(import.meta.url)){const a=process.argv.slice(2),opt=n=>a.includes(n)?a[a.indexOf(n)+1]:undefined,p=resolve(opt('--project')||'.');const result=a.includes('--track')?trackBlock(p,opt('--track'),opt('--path')):planUpgrade(p,{apply:a.includes('--apply')});console.log(JSON.stringify(result,null,2));if(result.status==='conflict')process.exitCode=1;}
