#!/usr/bin/env node
// design-lint.mjs — shine enforcement, wired as a Claude Code PostToolUse hook.
//
// Reads the hook event JSON on stdin, lints the written file, and either:
//   - hard-blocks (decision: "block") for off-token color literals and
//     arbitrary Tailwind values, or
//   - soft-flags (additionalContext) for off-scale px values.
//
// Also runnable directly:  node design-lint.mjs <file...>   (exit 1 on violations)
//
// Escapes: a `shine-lint: off` comment in the first five lines of a file,
// files under tokens/, dist/, node_modules/, corpus dirs, or generated files.

import { readFileSync } from "node:fs";
import { basename, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const DESIGN_EXT = /\.(tsx|jsx|css|html|svelte|vue)$/;

// A UI is not identified by its file extension. Host languages can embed HTML/CSS in
// string literals (Python, Go, Ruby templates) — which sailed past this
// lint for months on `.py` alone while accumulating 56 raw hex values and a 5/7/9/11/13px
// spacing set. Any host language can carry a stylesheet, so these are linted too, but only
// when the file actually contains markup or declarations (below), or every backend module
// with a `#` comment becomes a false positive.
// Markdown is deliberately absent: prose that documents a rule has to be able to quote the
// value it forbids. Including it blocked edits to shine's own references (43 hits) and to
// this skill's SKILL.md — a lint that cannot be documented is a lint nobody will keep.
const EMBEDS_UI_EXT = /\.(py|ts|js|mjs|cjs|go|rb|php|java|kt|kts|ex|exs|rs|erb|jinja|j2|hbs|mustache|twig|blade|astro)$/;

// Markers of a real embedded stylesheet or document. Deliberately demanding: a `<style>`
// or `<html>` block, or a CSS rule/at-rule shape, not merely an angle bracket.
const UI_MARKER =
  /<style[\s>]|<\/style>|<!doctype html|<html[\s>]|<body[\s>]|<div[\s>]|@media\b|@keyframes\b|:root\s*\{|[.#][\w-]+\s*\{[^}]*:[^}]*;/i;

const EXEMPT_PATH =
  /(^|\/)(node_modules|dist|build|\.next|coverage|design-corpus|corpus|tokens\/(src|dist)|\.git)\//;

// The single answer to "is this file shine's business?", exported so stop-sweep.mjs
// asks it instead of keeping a second copy. It kept its own `.(tsx|jsx|css|html|svelte|vue)`
// list, so when this file learned to see UI embedded in .py the sweep did not — the same
// blindspot, one gate over, which is exactly how ui.py stayed invisible.
export function isDesignCandidate(path, readText = () => readFileSync(path, "utf8")) {
  if (EXEMPT_PATH.test(path)) return false;
  if (DESIGN_EXT.test(path)) return true;
  if (!EMBEDS_UI_EXT.test(path)) return false;
  try {
    return UI_MARKER.test(readText());
  } catch {
    return false; // deleted or unreadable — the lint will not run on it either
  }
}
const SPACE_SCALE = new Set([0, 1, 2, 4, 8, 12, 16, 24, 32, 48, 64]);

// utility-prefix + bracket: catches p-[13px], text-[#fff], w-[347px], grid-cols-[1fr_2fr]
// without matching plain array indexing in code.
const ARBITRARY = /(?<![\w$.])(?:-?(?:p|m|px|py|pt|pb|pl|pr|mx|my|mt|mb|ml|mr|w|h|size|min-w|max-w|min-h|max-h|text|bg|gap|gap-x|gap-y|space-x|space-y|rounded(?:-[a-z]+)?|top|left|right|bottom|inset(?:-[xy])?|leading|tracking|border(?:-[a-z]+)?|fill|stroke|shadow|z|grid-cols|grid-rows|basis|indent|scroll-m[a-z]*|outline|ring(?:-[a-z]+)?|decoration|divide-[xy]?|translate-[xy]|duration|delay|ease)-\[[^\]\n]+\])/g;

// raw color literals in CSS/style values
const RAW_HEX = /#[0-9a-fA-F]{3,8}\b/g;
const RAW_FUNC = /\b(?:rgba?|hsla?|oklch|oklab|lab|lch|hwb|color)\(/g;

// The token layer is where raw values are supposed to live — it is the definition,
// not a use. `tokens/dist/` is exempt by path, but apps that vendor a copy without a
// build step still got blocked 17 times on
// output written by the sync script itself. A gate that rejects its own source of
// truth teaches people to switch it off. Keyed on the generated header, so any
// vendored copy anywhere is covered without a path list to maintain.
// The scope in "@shine/" is optional on purpose: the sync script emits
// "Vendored from shine. DO NOT EDIT." while this regex only accepted
// "Vendored from @shine/". Every vendored copy in every consumer repo was
// therefore unprotected and blocked on its own generated content — the exact
// failure the exemption exists to prevent, reintroduced by a marker the emitter
// and the linter spelled differently. Matched against the file HEAD only, so the words appearing in
// prose further down cannot buy an exemption.
const TOKEN_LAYER = /GENERATED BY @shine\/tokens|Vendored from @?shine\b/i;

// The rules a pragma can switch off, by name. A pragma has to be able to name its
// reason, or the only available exception is "all of them" — which is what
// a consumer stylesheet did: a pragma whose stated reason was fixed widget geometry
// silently disabled colour and type in that file for months, while its own header
// claimed "values are shine tokens only".
const RULES = ["tailwind", "color", "type", "shadow", "spacing"];

// `shine-lint: off` -> every rule (still honoured; fixtures need it, and it is
// reported on every edit). `shine-lint: off shadow` / `off color,type` -> those only.
function pragma(head) {
  const m = /shine-lint:\s*off\b[ \t]*([\w,\s-]*)/.exec(head);
  if (!m) return null;
  const named = m[1]
    .split(/[,\s]+/)
    .map((s) => s.trim().toLowerCase())
    .filter((s) => RULES.includes(s));
  return { all: named.length === 0, off: new Set(named) };
}

function lint(path, text) {
  const head = text.split("\n", 8).join("\n");
  const off = pragma(head);
  if (off?.all) {
    return {
      hard: [],
      soft: [
        `${path}:1  exempt from shine entirely via \`shine-lint: off\` — every colour, type and ` +
          `shadow check is off here, not just the one you meant. Name the rule instead: ` +
          `\`shine-lint: off ${RULES.join("|")}\` (comma-separated), so the rest keep working`,
      ],
    };
  }
  if (TOKEN_LAYER.test(head)) return { hard: [], soft: [] };
  const enabled = (rule) => !off?.off.has(rule);

  const hard = [];
  const soft = [];
  // Block comments are stripped across the whole text, not per line: a comment that
  // *explains* a rule usually has to quote the value it forbids, and a multi-line one
  // was being read as code from its second line on. That reported `font-size:0` in a
  // comment written to justify removing a font-size:0. Newlines are preserved so line
  // numbers still point where a human is looking.
  //
  // Same reasoning extends to `<code>` and `<pre>` content and to HTML comments. Prose
  // that documents a rule has to be able to quote the value it forbids — which is why
  // markdown is exempt entirely — and shine's own site does exactly that: a paragraph
  // explaining why `text-[#1a1a1a]` erodes a token contract was itself reported as
  // eroding the token contract. Only the element *content* is masked, so an off-token
  // value in a `<code class="…">` attribute still blocks.
  const blank = (c) => c.replace(/[^\n]/g, " ");
  const masked = text
    .replace(/\/\*[\s\S]*?\*\//g, blank)
    .replace(/<!--[\s\S]*?-->/g, blank)
    .replace(/(<(code|pre)\b[^>]*>)([\s\S]*?)(<\/\2>)/gi, (_, open, __, body, close) =>
      open + blank(body) + close,
    );
  const lines = masked.split("\n");
  const isCSS = /\.css$/.test(path);
  // Where CSS declarations live: a stylesheet, a first-class design file, or a host file
  // carrying one. This gates type, tracking, shadow and off-scale spacing.
  //
  // It read `isCSS || (EMBEDS_UI_EXT && UI_MARKER)` — which excludes every extension in
  // DESIGN_EXT except .css. So `.html`, `.tsx`, `.jsx`, `.svelte` and `.vue` had the colour
  // rule and nothing else: a styled-jsx block or a <style> in an .html page could carry any
  // font-size, any letter-spacing, any hand-rolled shadow and any off-scale padding without
  // a word. The check meant to cover *more* files than .css was written so it covered
  // fewer, and the extension it was added for (.py) was the only one that gained anything.
  const pxScope = DESIGN_EXT.test(path) || (EMBEDS_UI_EXT.test(path) && UI_MARKER.test(text));

  lines.forEach((line, i) => {
    const n = i + 1;
    const noComment = line
      .replace(/\/\*.*?\*\//g, "")
      .replace(/(^|[^:])\/\/.*$/, "$1");

    // 1. arbitrary Tailwind values — the token contract exists so these never happen
    if (enabled("tailwind")) {
      for (const m of noComment.matchAll(ARBITRARY)) {
        hard.push(`${path}:${n}  arbitrary value \`${m[0]}\` — use a token utility (scale: 4/8/12/16/24/32/48/64, colors: bg/fg/primary/border…)`);
      }
    }

    // 2. raw color literals
    const inValue = isCSS ? /:\s*[^;{]*$/.test(noComment) || /:/.test(noComment) : true;
    if (inValue && enabled("color")) {
      for (const m of noComment.matchAll(RAW_HEX)) {
        hard.push(`${path}:${n}  raw hex \`${m[0]}\` — colors come from var(--shine-*) or a token utility`);
      }
      for (const m of noComment.matchAll(RAW_FUNC)) {
        // allow var()-driven wrappers: rgb(var(--x)), and CSS relative color syntax "from"
        const after = noComment.slice(m.index + m[0].length, m.index + m[0].length + 24);
        if (/^\s*(var\(|from\b)/.test(after)) continue;
        hard.push(`${path}:${n}  raw color \`${m[0]}…)\` — colors come from var(--shine-*) or a token utility`);
      }
    }

    // 3. literal font sizes. Type tokens exist since 2026-08-08, and until they did this
    // lint was silent about type entirely: `font-size:12px` is a legal *spacing* value, so
    // the off-scale check below could never see it. Five sizes in one stylesheet reached
    // production that way, then five more inline ones survived a tokenization pass because
    // nothing was checking. clamp()/calc() stay allowed — fluid display type is real.
    if (pxScope && enabled("type")) {
      for (const m of noComment.matchAll(/font-size\s*:\s*([^;}"'`]+)/g)) {
        const v = m[1].trim();
        if (/^(inherit|initial|unset|revert|smaller|larger|x?x-(small|large)|small|medium|large)$/.test(v)) continue;
        if (/var\(|clamp\(|calc\(|%$/.test(v)) continue;
        hard.push(
          `${path}:${n}  font-size \`${v}\` — type comes from var(--shine-text-xs|sm|base|lg|xl|2xl), ` +
            `or clamp() for fluid display type`,
        );
      }
      // Tracking is Rule 4's entire subject and had no tokens until 2026-08-09, so this
      // could not be checked and every surface shipped letter-spacing:0 or a one-off em.
      // The scale is keyed to the type scale: tracking-lg belongs with text-lg.
      for (const m of noComment.matchAll(/letter-spacing\s*:\s*([^;}"'`]+)/g)) {
        const v = m[1].trim();
        if (/^(inherit|initial|unset|revert|normal)$/.test(v)) continue;
        if (/var\(|calc\(/.test(v)) continue;
        hard.push(
          `${path}:${n}  letter-spacing \`${v}\` — tracking comes from ` +
            `var(--shine-tracking-xs|sm|base|lg|xl|2xl|caps), paired with the matching text-* size`,
        );
      }
    }

    // 4. hand-rolled elevation. The colour rule already blocks a raw rgba() shadow, but
    // `box-shadow: 0 2px 8px var(--shine-color-border)` passes every check while breaking
    // Rules 6 and 7 — one layer, no negative spread, no hairline ring. Rings are exempt:
    // a focus ring is 0 0 0 Npx and is not elevation. So is `inset`.
    if (pxScope && enabled("shadow")) {
      for (const m of noComment.matchAll(/box-shadow\s*:\s*([^;}"'`]+)/g)) {
        const v = m[1].trim();
        if (/^(none|inherit|initial|unset|revert)$/.test(v)) continue;
        if (/\binset\b/.test(v)) continue;
        // What is left after every var() reference is removed is the geometry the author
        // wrote by hand. `var(--shadow)` leaves nothing and is a token reference;
        // `0 2px 8px var(--border)` leaves `0 2px 8px` and is a hand-rolled single layer
        // wearing a token's colour, which every other check passes.
        const geometry = v.replace(/var\([^()]*(?:\([^()]*\)[^()]*)*\)/g, "").trim();
        if (!geometry) continue;
        // A pure ring: every offset and blur is zero, only the spread is non-zero.
        if (/^(?:0(?:px)?\s+){3}[\d.]+(?:px|rem|em)$/.test(geometry)) continue;
        hard.push(
          `${path}:${n}  hand-rolled box-shadow \`${v.slice(0, 48)}${v.length > 48 ? "…" : ""}\` — ` +
            `elevation comes from var(--shine-shadow-sm|md|lg), which carry the >=2 layers, the ` +
            `hairline ring and the negative spread that Rules 6 and 7 require`,
        );
      }
    }

    // 5. off-scale px in CSS declarations (soft: some geometry is legitimately free)
    if (pxScope && enabled("spacing")) {
      for (const m of noComment.matchAll(/:\s*[^;]*?(-?\d+(?:\.\d+)?)px/g)) {
        const v = Math.abs(parseFloat(m[1]));
        if (v > 2 && !SPACE_SCALE.has(v)) {
          soft.push(`${path}:${n}  ${m[1]}px is off the spacing scale (4/8/12/16/24/32/48/64) — intentional?`);
        }
      }
    }
  });

  return { hard, soft };
}

// shine's own SKILL.md is the one markdown file that gets checked, and for one thing only:
// that it has not been re-scoped. `paths:`/`globs:` make Cursor withhold the skill from every
// non-matching file, which is how the design authority went missing on host-language UI for months
// without a single error anywhere. Written-down invariants get re-broken; this one bites.
function lintSkillFrontmatter(path, text) {
  const end = text.indexOf("\n---\n", 4);
  if (!text.startsWith("---\n") || end === -1) return { hard: [], soft: [] };
  const hard = [];
  text
    .slice(4, end)
    .split("\n")
    .forEach((line, i) => {
      const m = /^(paths|globs)\s*:/.exec(line);
      if (m) {
        hard.push(
          `${path}:${i + 2}  \`${m[1]}:\` on the shine skill — it scopes the skill to matching ` +
            `files and Cursor then withholds it everywhere else. A path-gated authority is an ` +
            `absent authority. Remove it; frontmatter stays name + description.`,
        );
      }
    });
  return { hard, soft: [] };
}

function lintPath(path) {
  if (EXEMPT_PATH.test(path)) return { hard: [], soft: [] };
  // Resolve before matching: invoked as `design-lint.mjs SKILL.md` from the skill directory
  // the relative path missed the pattern and the check silently passed — a gate that only
  // bites through one of its two entry points is not a gate.
  if (/(^|\/)shine\/skill\/SKILL\.md$/.test(resolve(path))) {
    try {
      return { ...lintSkillFrontmatter(path, readFileSync(path, "utf8")), kind: "skill" };
    } catch {
      return { hard: [], soft: [] };
    }
  }
  const design = DESIGN_EXT.test(path);
  const maybeEmbedded = EMBEDS_UI_EXT.test(path);
  if (!design && !maybeEmbedded) return { hard: [], soft: [] };
  let text;
  try {
    text = readFileSync(path, "utf8");
  } catch {
    return { hard: [], soft: [] };
  }
  // A `.css` file is a stylesheet by definition. Every other host language has to prove it
  // is carrying one, or every backend module in the repo becomes a false positive.
  if (!design && !UI_MARKER.test(text)) return { hard: [], soft: [] };
  return lint(path, text);
}

// Everything below runs only when this file is the process entrypoint. Without the guard,
// `import { isDesignCandidate }` from another hook silently runs this script's hook mode in
// the importer's process: it consumed stop-sweep.mjs's stdin, saw no file path, and called
// process.exit(0) — the sweep reported clean on a file with raw hex in it.
const isEntrypoint =
  process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

// ---- direct CLI mode: any path argument wins; hook mode is stdin-only ----
if (isEntrypoint && process.argv.length > 2) {
  let bad = false;
  for (const p of process.argv.slice(2)) {
    const { hard, soft } = lintPath(p);
    hard.forEach((v) => (bad = true, console.error(`BLOCK ${v}`)));
    soft.forEach((v) => console.error(`note  ${v}`));
  }
  process.exit(bad ? 1 : 0);
}

// ---- hook mode: stdin event, Claude Code PostToolUse or Cursor afterFileEdit ----
// Both surfaces get the same lint from one script. Wiring only Claude Code is how Cursor ran
// with zero shine enforcement on every file until 2026-08-08 — the parity rule exists
// precisely because one surface updated alone always becomes the stale one.
//
// The two differ in both directions: Cursor puts the path at the top level and blocks on
// exit code 2, Claude Code nests it under tool_input and blocks with a JSON decision.
function eventPath(event) {
  return (
    event?.tool_input?.file_path || // Claude Code PostToolUse
    event?.file_path || // Cursor afterFileEdit
    event?.path ||
    event?.edits?.[0]?.file_path ||
    null
  );
}

const isCursor = (event) =>
  typeof event?.hook_event_name === "string"
    ? /afterFileEdit|afterTabFileEdit/i.test(event.hook_event_name)
    : !event?.tool_input && Boolean(event?.file_path || event?.path);

// hook events deliver stdin immediately; if nothing arrives, we were invoked
// wrong (no args, no event) — exit instead of waiting forever
const stdinGuard = isEntrypoint ? setTimeout(() => process.exit(0), 5000) : null;
let input = "";
if (isEntrypoint) process.stdin.on("data", (c) => (input += c));
if (isEntrypoint) process.stdin.on("end", () => {
  clearTimeout(stdinGuard);
  let event;
  try {
    event = JSON.parse(input);
  } catch {
    process.exit(0);
  }
  const path = eventPath(event);
  if (!path) process.exit(0);
  const { hard, soft, kind } = lintPath(path);
  // The frontmatter invariant is not pragma-escapable, so it must not be told it is.
  const remedy =
    kind === "skill"
      ? "Delete the key. The frontmatter stays `name` + `description` only."
      : "Fix by replacing literals with shine tokens (var(--shine-*) in CSS, token utilities in " +
        "Tailwind). If a value is genuinely outside the system, add a scoped pragma naming the " +
        `one rule — \`shine-lint: off ${RULES.join("|")}\` — in the first five lines, and say why. ` +
        "A bare `shine-lint: off` disables all of them and is almost never what you mean.";
  const headline =
    kind === "skill"
      ? `shine: ${basename(path)} has been re-scoped and would stop loading:`
      : `shine design-lint: ${basename(path)} has off-token values that must be fixed:`;

  if (isCursor(event)) {
    // Cursor: stderr carries the message, exit 2 blocks. There is no documented
    // permission field on afterFileEdit, so the exit code is the whole contract.
    if (hard.length) {
      process.stderr.write(
        `${headline}\n` +
          hard.slice(0, 12).map((v) => `  - ${v}`).join("\n") +
          (hard.length > 12 ? `\n  …and ${hard.length - 12} more` : "") +
          `\n${remedy}\n`,
      );
      process.exit(2);
    }
    if (soft.length) {
      process.stderr.write(
        `shine design-lint notes for ${basename(path)}:\n` +
          soft.slice(0, 8).map((v) => `  - ${v}`).join("\n") +
          "\n",
      );
    }
    process.exit(0);
  }

  if (hard.length) {
    process.stdout.write(
      JSON.stringify({
        decision: "block",
        reason:
          `${headline}\n` +
          hard.slice(0, 12).map((v) => `  - ${v}`).join("\n") +
          (hard.length > 12 ? `\n  …and ${hard.length - 12} more` : "") +
          `\n${remedy}`,
      }),
    );
    process.exit(0);
  }
  if (soft.length) {
    process.stdout.write(
      JSON.stringify({
        hookSpecificOutput: {
          hookEventName: "PostToolUse",
          additionalContext:
            `shine design-lint notes for ${basename(path)}:\n` +
            soft.slice(0, 8).map((v) => `  - ${v}`).join("\n"),
        },
      }),
    );
  }
  process.exit(0);
});
