import { HEADER, literalTokens, pick } from './lib.mjs';

// Email target. The renderer is the constraint: tables, inline styles,
// no custom properties, no flexbox in Outlook. Emits:
//   email.json   flat literal map for any inliner
//   email.html   bulletproof starter — 600px table skeleton, all styles inline
// The plugin asserts its own constraints: zero var(), zero custom properties,
// zero flex/grid in the HTML output.
export default function email({ jsonFile, htmlFile, lane }) {
  return {
    name: 'shine:email',
    enforce: 'post',
    async build({ getTransforms, outputFile }) {
      const t = literalTokens(getTransforms);

      const bg = pick(t, 'color.bg');
      const bgSubtle = pick(t, 'color.bg-subtle', 'color.bg');
      const fg = pick(t, 'color.fg');
      const fgMuted = pick(t, 'color.fg-muted', 'color.fg');
      const border = pick(t, 'color.border', 'color.fg-muted');
      const primary = pick(t, 'color.primary');
      const primaryFg = pick(t, 'color.primary-fg', 'color.bg');
      const header = pick(t, 'color.brand.anchor', 'color.bg-subtle', 'color.bg');
      const headerFg = pick(t, 'color.brand.canvas', 'color.bg');
      const body = pick(t, 'font.body', 'font.sans');
      const display = pick(t, 'font.display', 'font.serif', 'font.body', 'font.sans');
      const radius = pick(t, 'radius.md', 'radius.sm') ?? '8px';
      for (const [name, v] of Object.entries({ bg, fg, primary, body }))
        if (!v) throw new Error(`email: lane "${lane}" is missing a required token for ${name}`);

      outputFile(
        jsonFile,
        JSON.stringify(
          {
            $comment: 'GENERATED BY @shine/tokens. DO NOT EDIT. Literal values for email inlining.',
            lane,
            tokens: Object.fromEntries(t),
          },
          null,
          2,
        ) + '\n',
      );

      const html = `<!doctype html>
<!-- ${HEADER(`@shine/${lane} email starter`).replace(/\/\*|\*\//g, '').trim()} -->
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="x-apple-disable-message-reformatting">
<title></title>
</head>
<body style="margin:0; padding:0; background-color:${bgSubtle};">
  <div style="display:none; max-height:0; overflow:hidden; mso-hide:all;">Preheader copy — front-load the outcome.</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="${bgSubtle}" style="background-color:${bgSubtle};">
    <tr><td align="center" style="padding:24px 12px;">
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" bgcolor="${bg}" style="width:600px; max-width:100%; background-color:${bg}; border:1px solid ${border};">
        <tr>
          <td bgcolor="${header}" style="background-color:${header}; padding:20px 32px;">
            <span style="font-family:${display}; font-size:18px; line-height:24px; color:${headerFg}; font-weight:bold;">Sender name</span>
          </td>
        </tr>
        <tr>
          <td style="padding:32px;">
            <h1 style="margin:0 0 16px; font-family:${display}; font-size:24px; line-height:32px; color:${fg};">Headline states the outcome</h1>
            <p style="margin:0 0 16px; font-family:${body}; font-size:16px; line-height:24px; color:${fg};">One idea per paragraph. Front-load the first two words. Say what happens when they click.</p>
            <table role="presentation" cellpadding="0" cellspacing="0" border="0">
              <tr><td id="cta" bgcolor="${primary}" style="background-color:${primary}; border-radius:${radius}; mso-padding-alt:12px 24px;">
                <a href="https://example.com" style="display:inline-block; padding:12px 24px; font-family:${body}; font-size:16px; line-height:24px; font-weight:bold; color:${primaryFg}; text-decoration:none;">Verb + outcome</a>
              </td></tr>
            </table>
            <p style="margin:16px 0 0; font-family:${body}; font-size:13px; line-height:20px; color:${fgMuted};">Answer the anxiety here — what happens after the click, in one line.</p>
          </td>
        </tr>
        <tr>
          <td style="padding:20px 32px; border-top:1px solid ${border};">
            <p style="margin:0; font-family:${body}; font-size:12px; line-height:18px; color:${fgMuted};">Footer: postal address and unsubscribe link — both are legally required.</p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>
`;
      for (const banned of ['var(', '--shine', 'display:flex', 'display:grid', 'display: flex', 'display: grid'])
        if (html.includes(banned)) throw new Error(`email: output contains "${banned}"`);
      outputFile(htmlFile, html);
    },
  };
}
