import { literalTokens, pick, firstFamily } from './lib.mjs';

// Google Docs target. Docs has no CSS and no token API — the emit is an Apps
// Script that applies token-derived attributes to the standard named styles
// (TITLE, HEADING1–3, NORMAL_TEXT) across the active document. Fonts must be
// families Google Docs can serve; unavailable families silently no-op, so the
// header documents each mapping.
//
// Sizes were absent here on the stated grounds that "the lanes carry no
// type-scale tokens". They have carried one since 2026-08-08, and this comment
// went on justifying the gap for a day after the gap closed — a consumer that
// documents a reason rather than reading the tokens goes stale silently. Points
// now, derived: Docs measures in pt, so px * 0.75.
const PT = (rem) => Math.round(parseFloat(rem) * 16 * 0.75 * 2) / 2;

export default function gdocs({ filename, lane }) {
  return {
    name: 'shine:gdocs',
    enforce: 'post',
    async build({ getTransforms, outputFile }) {
      const t = literalTokens(getTransforms);
      const fg = pick(t, 'color.fg');
      const fgMuted = pick(t, 'color.fg-muted', 'color.fg');
      const primary = pick(t, 'color.primary');
      const link = pick(t, 'color.info', 'color.primary');
      const displayFont = firstFamily(pick(t, 'font.display', 'font.serif', 'font.sans'));
      const bodyFont = firstFamily(pick(t, 'font.body', 'font.sans'));
      const monoFont = firstFamily(pick(t, 'font.mono') ?? 'Roboto Mono');
      if (!fg || !primary) throw new Error(`gdocs: lane "${lane}" missing fg/primary`);
      const size = Object.fromEntries(
        ['xs', 'sm', 'base', 'lg', 'xl', '2xl'].map((k) => [k, PT(pick(t, `text.${k}`))]),
      );
      for (const [k, v] of Object.entries(size))
        if (!Number.isFinite(v)) throw new Error(`gdocs: lane "${lane}" missing text.${k}`);

      outputFile(
        filename,
        `/**
 * @shine/${lane} → Google Docs theme.
 * GENERATED BY @shine/tokens. DO NOT EDIT — edit src/*.tokens.json and run \`npm run build\`.
 *
 * Install: extensions → Apps Script on the target doc (or a template doc),
 * paste this file, run applyShineTheme(). Re-run after edits to restyle.
 *
 * Font notes: Docs applies only families it can serve; unknown families
 * silently keep the prior font. Display "${displayFont}" / body "${bodyFont}"
 * come straight from the ${lane} lane tokens — if a family is unavailable in
 * Docs, that is a token-level decision, not one this script should make.
 */

var SHINE = {
  lane: ${JSON.stringify(lane)},
  color: {
    fg: ${JSON.stringify(fg)},
    fgMuted: ${JSON.stringify(fgMuted)},
    primary: ${JSON.stringify(primary)},
    link: ${JSON.stringify(link)},
  },
  font: {
    display: ${JSON.stringify(displayFont)},
    body: ${JSON.stringify(bodyFont)},
    mono: ${JSON.stringify(monoFont)},
  },
  // Point sizes from the text.* scale (px x 0.75). Docs has no line-height
  // attribute per named style, so leading.* has no target here.
  size: ${JSON.stringify(size)},
};

function shineStyles_() {
  var A = DocumentApp.Attribute;
  var base = {};
  base[A.FONT_FAMILY] = SHINE.font.body;
  base[A.FOREGROUND_COLOR] = SHINE.color.fg;
  base[A.FONT_SIZE] = SHINE.size.base;

  var heading = function (pt) {
    var h = {};
    h[A.FONT_FAMILY] = SHINE.font.display;
    h[A.FOREGROUND_COLOR] = SHINE.color.fg;
    h[A.BOLD] = true;
    h[A.FONT_SIZE] = pt;
    return h;
  };

  var subtle = {};
  subtle[A.FONT_FAMILY] = SHINE.font.body;
  subtle[A.FOREGROUND_COLOR] = SHINE.color.fgMuted;
  subtle[A.FONT_SIZE] = SHINE.size.lg;

  var H = DocumentApp.ParagraphHeading;
  var styles = {};
  styles[H.NORMAL] = base;
  styles[H.TITLE] = heading(SHINE.size['2xl']);
  styles[H.HEADING1] = heading(SHINE.size.xl);
  styles[H.HEADING2] = heading(SHINE.size.lg);
  styles[H.HEADING3] = heading(SHINE.size.base);
  styles[H.SUBTITLE] = subtle;
  return styles;
}

/** Apply the ${lane} lane to every paragraph of the active document. */
function applyShineTheme() {
  var doc = DocumentApp.getActiveDocument();
  var styles = shineStyles_();
  var paragraphs = doc.getBody().getParagraphs();
  for (var i = 0; i < paragraphs.length; i++) {
    var p = paragraphs[i];
    var s = styles[p.getHeading()];
    if (s) p.setAttributes(s);
  }
  var linkStyle = {};
  linkStyle[DocumentApp.Attribute.FOREGROUND_COLOR] = SHINE.color.link;
  var text = doc.getBody().editAsText();
  var url = text.findText('https?://\\\\S+');
  while (url) {
    url.getElement().asText().setAttributes(url.getStartOffset(), url.getEndOffsetInclusive(), linkStyle);
    url = text.findText('https?://\\\\S+', url);
  }
}
`,
      );
    },
  };
}
