import { FORMAT_ID as FORMAT_CSS } from '@terrazzo/plugin-css';
import { parse, formatHex, formatRgb } from 'culori';

export { FORMAT_CSS };

export const HEADER = (what) => `/* -------------------------------------------------------
 * ${what}
 * GENERATED BY @shine/tokens. DO NOT EDIT — edit src/*.tokens.json
 * and run \`npm run build\`.
 * ------------------------------------------------------- */`;

/** CSS transforms for one mode ('.' = default), keyed by token id. */
export function cssTransforms(getTransforms, mode = '.') {
  return getTransforms({ format: FORMAT_CSS, id: '*', mode });
}

/** Canonical human value: hex for opaque colors, rgba() for alpha, else the CSS value. */
export function canonicalValue(cssValue) {
  if (typeof cssValue !== 'string') return String(cssValue);
  const parsed = parse(cssValue);
  if (parsed && (parsed.mode === 'rgb' || parsed.mode === 'srgb')) {
    return parsed.alpha !== undefined && parsed.alpha < 1 ? formatRgb(parsed) : formatHex(parsed);
  }
  return cssValue;
}

/** Fully-dereferenced literal map: token id -> canonical literal (hex/rgba/CSS string). */
export function literalTokens(getTransforms, mode = '.') {
  const defaults = cssTransforms(getTransforms, '.');
  const varMap = Object.fromEntries(
    [...defaults, ...(mode === '.' ? [] : cssTransforms(getTransforms, mode))].map((t) => [
      t.localID,
      t.value,
    ]),
  );
  const deref = (value) => {
    let v = value;
    for (let hop = 0; hop < 10; hop++) {
      const m = typeof v === 'string' && v.match(/^var\((--[\w-]+)\)$/);
      if (!m) return v;
      v = varMap[m[1]];
    }
    throw new Error(`lib: unresolvable var() chain from "${value}"`);
  };
  const rows = mode === '.' ? defaults : cssTransforms(getTransforms, mode);
  return new Map(rows.map((t) => [t.id, canonicalValue(deref(t.value))]));
}

/** First font family from a CSS font stack literal, unquoted. */
export function firstFamily(stack) {
  if (typeof stack !== 'string') return String(stack);
  return stack.split(',')[0].trim().replace(/^['"]|['"]$/g, '');
}

/** First present id from candidates, else undefined. */
export function pick(map, ...ids) {
  for (const id of ids) if (map.has(id)) return map.get(id);
  return undefined;
}
