import { literalTokens, pick, firstFamily } from './lib.mjs';

// Office target (brand lane). The consumable seam for the docx/pptx/xlsx
// brand writers: an Office-theme-shaped palette (the dk/lt/accent slots any
// OOXML theme uses) plus the full literal token map. Writers read this file
// instead of carrying hardcoded hexes. Only slots the lane actually has are
// emitted — consumers keep their own defaults for the rest.
export default function office({ filename, lane }) {
  return {
    name: 'shine:office',
    enforce: 'post',
    async build({ getTransforms, outputFile }) {
      const t = literalTokens(getTransforms);
      const slots = {
        dk1: pick(t, 'color.fg'),
        lt1: pick(t, 'color.bg'),
        dk2: pick(t, 'color.brand.anchor', 'color.info'),
        lt2: pick(t, 'color.bg-subtle'),
        accent1: pick(t, 'color.primary'),
        accent2: pick(t, 'color.info'),
        hlink: pick(t, 'color.info', 'color.primary'),
        folHlink: pick(t, 'color.fg-muted'),
      };
      for (const k of Object.keys(slots)) if (slots[k] === undefined) delete slots[k];
      if (!slots.dk1 || !slots.lt1 || !slots.accent1)
        throw new Error(`office: lane "${lane}" missing dk1/lt1/accent1`);

      outputFile(
        filename,
        JSON.stringify(
          {
            $comment:
              'GENERATED BY @shine/tokens. DO NOT EDIT. Office theme slots + literal token map for the docx/pptx/xlsx writers.',
            lane,
            theme: {
              colors: slots,
              fonts: {
                major: firstFamily(pick(t, 'font.display', 'font.serif', 'font.sans')),
                minor: firstFamily(pick(t, 'font.body', 'font.sans')),
              },
            },
            tokens: Object.fromEntries(t),
          },
          null,
          2,
        ) + '\n',
      );
    },
  };
}
