import { canonicalValue, cssTransforms } from './lib.mjs';

// Python constants target (apps that serve CSS from Python). Opaque colors emit as hex,
// alpha colors as rgba(); dimensions/durations/fonts as CSS strings.
export default function python({ filename, lane, modes = [] }) {
  return {
    name: 'shine:python',
    enforce: 'post',
    async build({ getTransforms, outputFile }) {
      // CSS transforms carry aliases as var() references; Python needs literals.
      const varMap = (mode) =>
        Object.fromEntries(cssTransforms(getTransforms, mode).map((t) => [t.localID, t.value]));
      const defaults = varMap('.');
      const entries = (mode) => {
        const map = mode === '.' ? defaults : { ...defaults, ...varMap(mode) };
        const deref = (value) => {
          let v = value;
          for (let hop = 0; hop < 10; hop++) {
            const m = typeof v === 'string' && v.match(/^var\((--[\w-]+)\)$/);
            if (!m) return v;
            v = map[m[1]];
          }
          throw new Error(`python: unresolvable var() chain from "${value}"`);
        };
        return cssTransforms(getTransforms, mode).map((t) => [t.id, canonicalValue(deref(t.value))]);
      };
      const dict = (pairs, indent = '    ') =>
        pairs.map(([k, v]) => `${indent}${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n');

      const base = entries('.');
      const constants = base
        .map(([id, v]) => `${id.replace(/[.-]/g, '_').toUpperCase()} = ${JSON.stringify(v)}`)
        .join('\n');

      let modeDicts = '';
      for (const { mode } of modes) {
        const overrides = entries(mode);
        if (overrides.length) {
          modeDicts += `\n${mode.replace(/[.-]/g, '_').toUpperCase()}: dict[str, str] = {\n${dict(overrides)}\n}\n`;
        }
      }

      outputFile(
        filename,
        `"""@shine/${lane} design tokens.

GENERATED BY @shine/tokens. DO NOT EDIT — edit src/*.tokens.json
and run \`npm run build\`.
"""

TOKENS: dict[str, str] = {
${dict(base)}
}
${modeDicts}
${constants}
`,
      );
    },
  };
}
