import { createRequire } from 'node:module';
import { converter, clampChroma, formatHex, parse } from 'culori';
import { HEADER, literalTokens } from './lib.mjs';

const require = createRequire(import.meta.url);

// Salesforce target (brand lane). Not a stylesheet — SLDS 2 has no
// supported org-wide CSS injection point. Emits:
//   salesforce.md    brand-palette spec an admin transcribes once
//   salesforce.css   per-component fallback block for LWCs we own
//   salesforce.json  machine-readable ramp + hook map
// Authority is @salesforce-ux/design-tokens flat.json (research/salesforce.md
// rule 5: never hand-maintain a mapping table). Method: keep each Cosmos brand
// step's OKLCH lightness — that ladder carries SLDS's designed contrast
// relationships — and re-seed hue + chroma from our brand accent, scaling the
// Cosmos ramp's own chroma profile so the curve shape survives the hue swap.
const toOklch = converter('oklch');

export default function salesforce({ mdFile, cssFile, jsonFile, lane, seedToken }) {
  return {
    name: 'shine:salesforce',
    enforce: 'post',
    async build({ getTransforms, outputFile }) {
      const theme = 'cosmos';
      const pkg = require('@salesforce-ux/design-tokens/package.json');
      const flat = require(
        `@salesforce-ux/design-tokens/dist/themes/${theme}/${theme}.global.tokens.flat.json`,
      );
      const entries = Array.isArray(flat) ? flat : Object.values(flat);

      const literals = literalTokens(getTransforms);
      const seedHex = literals.get(seedToken);
      if (!seedHex) throw new Error(`salesforce: seed token "${seedToken}" not in lane "${lane}"`);
      const seed = toOklch(parse(seedHex));

      // --- the 17 reference brand steps, straight from the authority file
      const steps = entries
        .filter((e) => /^slds-r-color-brand-\d+$/.test(e.name) && !e.deprecated)
        .map((e) => ({ ...e, n: Number(e.name.match(/(\d+)$/)[1]) }))
        .sort((a, b) => a.n - b.n);
      if (steps.length !== 17)
        throw new Error(`salesforce: expected 17 brand reference steps, got ${steps.length}`);

      const cosmos = steps.map((s) => toOklch(parse(s.value)));
      const chromaScale = seed.c / Math.max(...cosmos.map((c) => c.c));
      const nearest = cosmos.reduce(
        (best, c, i) => (Math.abs(c.l - seed.l) < Math.abs(cosmos[best].l - seed.l) ? i : best),
        0,
      );
      const ramp = steps.map((s, i) => ({
        hook: `--${s.name}`,
        step: s.n,
        cosmos: s.value,
        value:
          i === nearest
            ? formatHex(parse(seedHex))
            : formatHex(
                clampChroma(
                  { mode: 'oklch', l: cosmos[i].l, c: cosmos[i].c * chromaScale, h: seed.h },
                  'rgb',
                ),
              ),
      }));
      const byStep = Object.fromEntries(ramp.map((r) => [`--slds-r-color-brand-${r.step}`, r]));

      // --- derived global hooks: anything whose value points at a brand step
      const derived = entries
        .filter((e) => {
          const m = typeof e.value === 'string' && e.value.match(/^var\((--slds-r-color-brand-\d+)\)$/);
          return m && byStep[m[1]] && !e.deprecated;
        })
        .map((e) => ({
          hook: `--${e.name}`,
          via: e.value.match(/--slds-r-color-brand-\d+/)[0],
          value: byStep[e.value.match(/--slds-r-color-brand-\d+/)[0]].value,
          cssProperties: e.cssProperties ?? [],
        }));
      if (!derived.length) throw new Error('salesforce: no g-hooks resolved to brand steps');

      const brand = (id) => literals.get(id);
      const meta = {
        generatedFrom: `@salesforce-ux/design-tokens@${pkg.version} / ${theme}`,
        lane,
        seedToken,
        seedHex,
        method:
          'Cosmos step lightness kept; hue/chroma re-seeded from brand accent; chroma profile scaled; nearest-lightness step snapped to the exact seed; sRGB gamut-clamped by chroma reduction',
      };

      outputFile(
        jsonFile,
        JSON.stringify({ $comment: 'GENERATED BY @shine/tokens. DO NOT EDIT.', meta, ramp, derived }, null, 2) + '\n',
      );

      outputFile(
        cssFile,
        `${HEADER(`@shine/${lane} → Salesforce: per-component fallbacks for LWCs we own`)}

/* SLDS 2 prohibits overriding global (--slds-g-*) hooks, and there is no
 * supported org-wide CSS injection point. CONSUME the hook, fall back to the
 * shine literal so the component degrades cleanly on SLDS 1 orgs:
 *
 *   .cta { background: var(--slds-g-color-accent-1, var(--cs-brand-50)); }
 *
 * Scope this block inside the component (:host) — never globally. */
:host {
${ramp.map((r) => `  --cs-brand-${r.step}: ${r.value};`).join('\n')}
}
`,
      );

      outputFile(
        mdFile,
        `# Brand palette on Salesforce — transcription spec

GENERATED BY @shine/tokens from \`${meta.generatedFrom}\`. DO NOT EDIT.

SLDS 2 has **no supported org-wide CSS injection point**: overriding global
\`--slds-g-*\` hooks is explicitly prohibited by Salesforce. The sanctioned
global path is the **Themes and Branding** setup UI — a human transcribes the
values below once. Per-component CSS for LWCs we own uses \`salesforce.css\`.

## Seed decision

Brand ramp is seeded from \`${seedToken}\` (${seedHex}) — the *action* accent —
because in Cosmos the brand ramp drives the interactive accent system
(buttons, links, selection), and the org's existing customizations already use
this hex for exactly that. Navy (${brand('color.brand.navy') ?? 'n/a'}) carries identity
surfaces (global header) below, not the accent ramp.

## Themes and Branding (Setup → Themes and Branding)

| Field | Value | Source token |
|---|---|---|
| Brand Color | ${seedHex} | ${seedToken} |
| Global Header Background | ${brand('color.brand.anchor') ?? brand('color.brand.navy')} | color.brand.anchor |
| Page Background | ${brand('color.bg-subtle') ?? brand('color.bg')} | color.bg-subtle |

## Brand reference ramp — the 17 \`--slds-r-color-brand-*\` steps

Cosmos lightness ladder kept (it carries SLDS's designed contrast
relationships); hue/chroma from the seed; step ${ramp[nearest].step} is the exact seed.

| Hook | Cosmos default | Brand value |
|---|---|---|
${ramp.map((r) => `| \`${r.hook}\` | \`${r.cosmos}\` | \`${r.value}\` |`).join('\n')}

## Global hooks this recolors (consume-only — never override)

Resolved from the authority file's own \`var()\` chains; ${derived.length} hooks.

| Hook | Via | Value | Legal on |
|---|---|---|---|
${derived
  .map((d) => `| \`${d.hook}\` | \`${d.via}\` | \`${d.value}\` | ${d.cssProperties.slice(0, 4).join(', ') || '—'} |`)
  .join('\n')}

## Rules that keep this safe

1. Never set \`--slds-g-*\`, \`--slds-s-*\`, or \`--_slds-*\` — prohibited tiers.
2. LWC CSS consumes hooks with shine fallbacks: \`var(--slds-g-color-accent-1, var(--cs-brand-50))\`.
3. Run \`slds-linter\` before shipping component CSS; read \`no-unsupported-hooks-slds2\` fixes as **deletions**.
4. This file is regenerated by \`npm run build\` — a Salesforce theme update changes the defaults, so re-diff after upgrading \`@salesforce-ux/design-tokens\`.
`,
      );
    },
  };
}
