import assert from "node:assert/strict";
import {createDesignPacket} from "../core/design-packet.mjs";
const grid=createDesignPacket({job:"fraud claims review queue datagrid",lane:"internal",project:process.cwd()});
assert.equal(grid.category,"datagrid");
assert.match(grid.selected.id,/datatable|crud|untitled-table/i);
for(const item of ["search","sort","filters","column visibility","pagination","row selection","row actions"])assert(grid.controlInventory.includes(item),item);
assert.deepEqual(grid.requiredStates,["loading","empty","error","populated"]);
assert(grid.candidates.length>0&&grid.candidates.length<=3);
assert(grid.selected.paths.sourceExcerpts.length>0);
assert(grid.selected.paths.sourceExcerpts.every(x=>x.excerpt.length<=1200));
assert(grid.examples.some(x=>x.sourceFile.endsWith("application/table/table.demo.tsx")));
assert.match(grid.starter,/full-table\.html$/);
assert.match(grid.proof.artifactAttribute,/data-cite/);
const hybrid=createDesignPacket({job:"Untitled UI + shadcn CEO judgment queue datagrid",lane:"internal",project:process.cwd()});
assert.equal(hybrid.selected.id,"untitled-table");
assert.notEqual(hybrid.selected.id,"carbon-datatable");
const form=createDesignPacket({job:"insurance application form",lane:"saas",project:process.cwd()});
assert.equal(form.category,"form");assert(form.controlInventory.includes("validation"));
const dashboard=createDesignPacket({job:"analytics dashboard line charts",lane:"internal",project:process.cwd()});
assert(dashboard.candidates.some(x=>x.id==="untitled-line-charts"),"Untitled dashboard is not a primary candidate");
assert(dashboard.examples.some(x=>x.sourceFile.includes("application/charts/")),"Untitled chart examples missing from packet");
assert.throws(()=>createDesignPacket({job:""}),/job is required/);
console.log("design packet PASS: bounded sources, job structure, controls, states, provenance");
