import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,symlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {selectImplementation} from '../integrations/library-select.mjs';
import {surfaceCensus,validateSurfaceContract,verifySurfaceReceipt} from '../integrations/surface-audit.mjs';
import {trackBlock,planUpgrade,digest,adaptSource} from '../integrations/upgrade.mjs';
import {checkCompatibility} from '../integrations/compatibility.mjs';
const project=mkdtempSync(join(tmpdir(),'shine-system-tools-'));const put=(path,value)=>{mkdirSync(join(project,path,'..'),{recursive:true});writeFileSync(join(project,path),typeof value==='string'?value:JSON.stringify(value));};
try{
 put('package.json',{name:'fixture'});put('components.json',{$schema:'https://ui.shadcn.com/schema.json',aliases:{ui:'@/components/ui'},tailwind:{prefix:'nx'}});put('tsconfig.json',{compilerOptions:{jsx:'react-jsx',moduleResolution:'bundler',baseUrl:'.',paths:{'@/*':['src/*']}}});put('src/app/page.tsx','import {DataGrid} from "../components/grid"; export default function Page(){return <DataGrid/>}');put('src/components/grid.tsx','export function DataGrid(){return <table><tbody/></table>}');put('src/app/globals.css',':root {--background: white;--foreground: black;}');
 const selection=selectImplementation(project,'record table');assert.equal(selection.selected.tier,'product');assert.equal(selection.selected.export,'DataGrid');assert.equal(selection.customWork.allowed,false);assert.equal(selectImplementation(project,'remote record table').selected.pattern,'server-data-grid');assert.equal(selectImplementation(project,'record table',{pattern:'server-data-grid'}).selected.tier,'shine');
 put('src/components/owner-lookup.tsx','export function OwnerLookup(){return <div/>}');assert.equal(selectImplementation(project,'owner lookup').selected.export,'OwnerLookup');
 const licensed=selectImplementation(project,'tailwind application').candidates.find(row=>row.access==='licensed');assert.equal(licensed.available,false);
 let census=surfaceCensus(project);assert.equal(census.routes.length,1);assert.equal(census.controls.length,2);
 const contract={version:1,buildHeader:'x-shine-source-commit',routes:[{id:'home',source:'src/app/page.tsx',url:'/',requiredStates:['ready'],states:[{id:'ready',steps:[{action:'visible',selector:'table'}]}]}],controlOwners:[{source:'src/app/page.tsx',reason:'The route renders the shared grid directly for its primary workflow.',proofs:[{route:'home',state:'ready'}]},{source:'src/components/grid.tsx',reason:'The home route directly imports the shared record grid.',proofs:[{route:'home',state:'ready'}]}]};assert.equal(validateSurfaceContract(project,contract).status,'passed');
 put('src/app/new/page.tsx','export default function Page(){return <div/>}');assert.match(validateSurfaceContract(project,contract).errors.join(' '),/Unclassified route/);rmSync(join(project,'src/app/new'),{recursive:true});
 put('src/app/page.tsx','export default function Page(){return <div/>}');assert.match(validateSurfaceContract(project,contract).errors.join(' '),/does not import/);put('src/app/page.tsx','import {DataGrid} from "../components/grid"; export default function Page(){return <DataGrid/>}');
 const broken=structuredClone(contract);broken.routes[0].requiredStates.push('error');assert.match(validateSurfaceContract(project,broken).errors.join(' '),/Missing state/);
 const noAction=structuredClone(contract);noAction.routes[0].states.push({id:'error',steps:[{action:'visible',selector:'table'}]});assert.match(validateSurfaceContract(project,noAction).errors.join(' '),/real workflow action/);
 const initial=surfaceCensus(project).fingerprint;put('src/app/globals.css',':root {--background: black;}');assert.notEqual(surfaceCensus(project).fingerprint,initial);
 execFileSync('git',['init','-q',project]);execFileSync('git',['-C',project,'add','.']);execFileSync('git',['-C',project,'-c','user.name=Fixture','-c','user.email=fixture@example.test','commit','-qm','fixture']);const commit=execFileSync('git',['-C',project,'rev-parse','HEAD'],{encoding:'utf8'}).trim();
 // Synthetic receipt is a negative-control input only; not delivery evidence.
 const receipt={kind:'shine-surface-audit',version:1,sourceCommit:commit,createdAt:new Date().toISOString(),sourceFingerprint:surfaceCensus(project).fingerprint,contractSha256:digest(JSON.stringify(contract)),results:[390,1440].map(width=>({route:'home',state:'ready',width,status:'passed'}))};assert.equal(verifySurfaceReceipt(project,contract,receipt).status,'passed');assert.equal(verifySurfaceReceipt(project,contract,{...receipt,createdAt:'2000-01-01'}).status,'failed');assert.equal(verifySurfaceReceipt(project,contract,{...receipt,results:[...receipt.results,receipt.results[0]]}).status,'failed');
 symlinkSync(new URL('../node_modules',import.meta.url).pathname,join(project,'node_modules'));put('src/components/ui/button.tsx','export const Button:any=undefined');put('src/components/ui/input.tsx','export const Input:any=undefined');put('src/app/globals.css',':root {--background:white;--foreground:black;--border:gray;--muted-foreground:gray;--input:gray;}');
 const source=readFileSync(new URL('../blocks/filter-bar.tsx',import.meta.url),'utf8');put('src/components/filter-bar.tsx',adaptSource(source,'nx'));trackBlock(project,'filter-bar','src/components/filter-bar.tsx');assert.equal(planUpgrade(project).blocks[0].status,'current');put('src/components/filter-bar.tsx',adaptSource(source,'nx')+'\n// Product customization\n');assert.equal(planUpgrade(project,{apply:true}).blocks[0].status,'locally-modified');assert.match(readFileSync(join(project,'src/components/filter-bar.tsx'),'utf8'),/Product customization/);
 // Emulate an older upstream baseline while preserving a separate local edit.
 const baselinePath=join(project,'.shine/baselines/filter-bar.tsx'),manifestPath=join(project,'shine-installation.json');let manifest=JSON.parse(readFileSync(manifestPath,'utf8'));let old=readFileSync(baselinePath,'utf8').replace('Clear filters','Old clear label');writeFileSync(baselinePath,old);manifest.blocks[0].baselineSha256=digest(old);writeFileSync(manifestPath,JSON.stringify(manifest));put('src/components/filter-bar.tsx',old+'\n// Local footer\n');assert.equal(planUpgrade(project,{apply:true}).blocks[0].status,'merged');assert.match(readFileSync(join(project,'src/components/filter-bar.tsx'),'utf8'),/Local footer/);assert.match(readFileSync(join(project,'src/components/filter-bar.tsx'),'utf8'),/Clear filters/);
 manifest=JSON.parse(readFileSync(manifestPath,'utf8'));old=readFileSync(baselinePath,'utf8').replace('Clear filters','Old clear label');writeFileSync(baselinePath,old);manifest.blocks[0].baselineSha256=digest(old);writeFileSync(manifestPath,JSON.stringify(manifest));const local=old.replace('Old clear label','Product clear label');put('src/components/filter-bar.tsx',local);assert.throws(()=>planUpgrade(project,{apply:true}),/No files changed/);assert.equal(readFileSync(join(project,'src/components/filter-bar.tsx'),'utf8'),local);
 put('src/components/incompatible.tsx','import {Missing} from "@/components/ui/button";export function Broken(){return <Missing/>}');assert.match(checkCompatibility(project,['src/components/incompatible.tsx']).errors.join(' '),/no export Missing/);
 const outside=mkdtempSync(join(tmpdir(),'shine-outside-'));try{symlinkSync(outside,join(project,'escape'));assert.throws(()=>trackBlock(project,'date-range','escape/source.tsx'),/inside the project/);}finally{rmSync(outside,{recursive:true,force:true});}
 put('src/app/globals.css',':root {--background:white;}');put('src/components/bad.tsx','import {missing} from "package-that-does-not-exist";export function Bad(){return <div className="bg-background text-foreground"/>}');const compatibility=checkCompatibility(project,['src/components/bad.tsx']);assert.match(compatibility.errors.join(' '),/missing installed dependency/);assert.match(compatibility.errors.join(' '),/unprefixed utility/);assert.match(compatibility.errors.join(' '),/missing semantic token foreground/);
 console.log('system tools PASS: product selection, license gating, complete route census, disconnected proof, missing state, stale source/theme, stale and duplicate receipts, baseline integrity, preserved edits, merge conflicts, symlink escape and missing dependency/token/prefix controls');
}finally{rmSync(project,{recursive:true,force:true});}
